# Generated by Django 4.2.7 on 2023-12-05 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CriminalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name="Individual",
            new_name="Criminal",
        ),
        migrations.DeleteModel(
            name="Record",
        ),
        migrations.AddField(
            model_name="criminalcase",
            name="individual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.criminal"
            ),
        ),
        migrations.AddField(
            model_name="criminalcase",
            name="reported_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
