# Generated by Django 4.2.7 on 2023-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_criminalcase_rename_individual_criminal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criminal",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to="criminal_images/",
            ),
        ),
    ]
