# Generated by Django 4.2.7 on 2023-12-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_criminal_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criminal",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.png",
                null=True,
                upload_to="criminal_images/",
            ),
        ),
    ]
